name: CI Pipeline for JAR and API Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Repository Structure for e2eapi
      run: ls ./e2eapi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./e2eapi/package-lock.json

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ./e2eapi/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('e2eapi/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js dependencies
      working-directory: ./e2eapi
      run: npm ci

    - name: Debug Installed Dependencies
      working-directory: ./e2eapi
      run: npm list --depth=0

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

  run-jar:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run the JAR file
      working-directory: ./API
      run: |
        java -jar demo-0.0.1-SNAPSHOT.jar & 
        sleep 10 

  test-apis:
    runs-on: ubuntu-latest
    needs: [run-jar,setup]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ./e2eapi/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('e2eapi/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run Cucumber tests & Generate Allure results 
      working-directory: ./e2eapi
      run: npx cucumber-js
      continue-on-error: true 

    - name: Generate Allure Report
      working-directory: ./e2eapi
      run: npx allure generate allure-results --clean

    - name: Debug Allure Report Directory
      working-directory: ./e2eapi
      run: ls -R allure-report
  
  deploy-allure:
    runs-on: ubuntu-latest
    needs: [test-apis,setup]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Allure Report Directory
      working-directory: ./e2eapi
      run: ls -R allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./e2eapi/allure-report
        keep_files: false
